square/metrics

- query/README.md
> Updating README

- query/language.peg
- query/language.peg.go
- query/query_test.go
Modelled after JSON's floating point.
> better floating point implementation

- assert/assert.go
> Adding improvements to assert to support floats and booleans

- api/backend.go
- api/types.go
- api/types_test.go
* Adding `Backend` interface, which allows you to fetch data.
* Adding time series results and time range structs.
> Adding types to support backend data fetching

- query/command.go
- query/expression.go
- query/language.peg
- query/language.peg.go
- query/node.go
- query/parser.go
- query/parser_test.go
- query/query_test.go
Adding improvements to the query language parsing.
* Adding a command, `SelectCommand`.
* Adding an interface, `Expression` to aid the evaluation of the time series. No implementation is given yet.
* Adding go logic around select... statement grammar tree. Not done yet.
* Adding additional node structs, parser helpers, etc.
* Moving a block of parser tests to test command generation also.
@achow
> Adding parse tree support for parsing select statements

- query/language.peg
- query/language.peg.go
- query/node.go
- query/parser.go
> updating the grammar to store the group bys in the function invocations

- CONTRIBUTING.md
- README.md
Small PR, no semantical changes
CC: @achow
> Adding contributor file & updating README

- api/types.go
- api/types_test.go
- query/expression.go
- query/expression_test.go
- query/node.go
- query/parser.go
> Implement some Expressions

- query/language.peg
- query/language.peg.go
- query/query_test.go
As discussed, I changed the `range` clause to support (somewhat arbitrary) set of key-value pairs. nothing uses this yet, so only the grammar is changed. PTAL!
> changed the range clause to the concept of properties

- internal/errors.go
- internal/rules.go
- internal/rules_test.go
…(Rather than only a proper subset) are used in the pattern; add tests corresponding in rules_test.go to reflect this change
> Add flag to interpolateTags to check all tags in tagList are used

- api/backend/blueflood/blueflood.go
- api/predicate.go
- api/types.go
- main/query.go
- query/command.go
- query/expression.go
- query/expression_test.go
- query/node.go
- query/parser.go
- query/predicate.go
> Partially implement blueflood backend

- api/types.go
- query/join.go
- query/join_test.go
> implementation and testing of joins

- CONTRIBUTORS
- README.md
> Updating README, adding Nathan to the contributor list

- api/backend/blueflood/blueflood.go
- api/backend/blueflood/blueflood_test.go
- mocks/api.go
- mocks/http_client.go
> Add basic test for blueflood backend

- query/expression.go
- query/expression_test.go
@jeeyoungk  @achow 
Uses the join operation to compute binary functions (like the operators +, -, *, /).
> Nathanf join with binary expressions

- query/language.peg
- query/language.peg.go
- query/query_test.go
parenthesis were not working correctly with predicates. I fixed it.
> predicate parenthesis change

- query/command_test.go
- query/expression_test.go
- query/language.peg
- query/language.peg.go
I'm testing @Nathan-Fenner 's language change, and he is indeed correct - we've screwed up the operator precedence.
found some language bug regarding parenthesis - should fix it later.
> Adding tests for the predicate.

- query/expression.go
> Add Multiplication Operator

- query/language.peg.go
Ran `go get -u github.com/pointlander/peg`.
> Updating PEG

- query/command.go
- query/language.peg
- query/language.peg.go
- query/node.go
- query/parser.go
- query/query_test.go
Currently:
* implemented (initial) evaluation context assignment
Main issues/unexpected changes outside of implementation:
* The PEG grammar had to be modified in several places where it did not act as intended.
* The `SelectCommand` got a new member `context` which holds evaluation context information (but no backend)
* The `SelectCommand.Execute` method had to be modified accordingly
* The parser is very, very brittle when dealing with string literals; escaping characters and the quotes themselves are currently part of the parsed string. "Literal String" parsing should (ideally) substitute the source strings with their unescaped friends. Strings are currently like this: `"'this is a string \\' that has an escaped single quote'"`, which is hard to process.
* Parsing dates is fairly …
> Implement Evaluation Context Assignment and Parsing

- api/backend/blueflood/blueflood.go
> Updating logging to use standard logging instead of glog instead.

- api/backend/blueflood/blueflood.go
- api/predicate.go
- internal/errors.go
- internal/rules.go
- main/query.go
- mocks/api.go
- query/command.go
- query/expression.go
- query/expression_test.go
> Fix metric fetches

- query/expression.go
- query/transformation.go
Through the usage of `GetTransformation`, expression is now capable of performing transformation invocations.
> Expressions using Transformations

- api/predicate.go
- main/query.go
- query/command.go
- query/node.go
> Make Commands implement Node

- query/language.peg
- query/language.peg.go
- query/query_test.go
> Be tolerant of leading and trailing whitespace

- api/backend/blueflood/blueflood.go
- api/backend/blueflood/blueflood_test.go
This branch performs refactoring on the changes introduced by #60. The most important change is pulling from beyond the end of the timerange as in #62. 
> Refactoring & Pull Data from Past End of Timerange

- assert/assert.go
- query/command_test.go
> making integration tests of commands better by being more lenient on floating point errors

- main/common/common.go
- main/query.go
- main/ui.go
- query/command.go
- ui/ui.go
By visiting `/query?query=querytext` a user can query the MQE. (`NaN` in result causes a JSON encoding error).
> HTTP Queries

- .gitignore
- main/static/index.html
- main/static/script.js
- main/static/style.css
- query/command.go
- ui/ui.go
Serves static files in `/metrics/main/static`.
> Serve static files

- api/types.go
- api/types_test.go
> custom marshaller for timeseries, because it may contain NaN rows

- query/language.peg
- query/language.peg.go
- query/query_test.go
Fixes:
``select (x) where ...```
@Nathan-Fenner @achow
> parenthesis + where clause works now

- api/types.go
- api/types_test.go
I'm being a haxor by creating an anonymous struct!
> Timerange is marshal'ed as JSON correctly

- api/backend/blueflood/blueflood_test.go
- api/types.go
- api/types_test.go
- main/query.go
- query/aggregate/aggregate_test.go
- query/command.go
- query/command_test.go
- query/expression.go
- query/expression_test.go
- query/join_test.go
- query/parser.go
- query/transformation_test.go
> Add better library for the repl, use Timerange values everywhere

- main/static/index.html
- main/static/script.js
- main/static/style.css
- ui/ui.go
Google Charts (SVG) to render data.
> Charts for UI

- main/static/index.html
- main/static/script.js
- main/static/style.css
> Make the chart/input prettier

- query/command.go
- query/errors.go
- query/expression.go
- query/expression_test.go
- query/value.go
moving values to a separate file.
adding more structured error for invalid arguments.
> move values

- query/expression.go
For multiple-series fetches, performs the fetch in parallel, with a limited number of active fetches at a time. (Currently, 4).
> Parallel fetch

- query/language.peg
- query/language.peg.go
- query/parser.go
- query/parser_test.go
- query/query_test.go
> Add relative timestamp support

- query/command_test.go
- query/expression.go
- query/language.peg
- query/language.peg.go
- query/node.go
- query/parser.go
- query/query_test.go
Adds string literal nodes to the parse tree.
Also adds tests for `timeshift(...)`.
> String literal expression

- main/static/index.html
- main/static/script.js
- main/static/style.css
When the user presses the submit button, their query is saved in the hash of the URL, such as:
`http://localhost:8080/static/#select%20metric%20from%20'2015%2F6%2F10%2015%20PST'%20to%20'2015%2F6%2F10%2016%20PST'`
The URL can be copied/pasted and followed by other users. When opening a page with an encoded query, it is run immediately so that the results can be viewed on the page without having to press "submit".
Other additions:
* Error messages are shown
* While waiting for data to come back, shows a message
* While waiting for the chart to render, shows a message
* Cancels old request when a new one is made (if the request hadn't finished yet).
> Remember query in url #hash

- api/api.go
- api/backend/blueflood/blueflood.go
- api/backend/blueflood/blueflood_test.go
- api/types.go
- internal/api.go
- main/common/common.go
- main/query.go
- main/ruletester.go
- main/ui.go
> Add support for configured ttl, standardize on configs

- api/backend/blueflood/blueflood.go
- api/backend/blueflood/blueflood_test.go
- mocks/http_client.go
* all the errors are instances of BackendError.
* added tests for common error cases (timeout, etc).
> Better error handling on blueflood side.

- query/aggregate/aggregate.go
- query/aggregate/aggregate_test.go
- query/expression.go
- query/expression_test.go
- query/function.go
- query/transformation.go
No unit tests yet. Existing tests for expressions are still standing, however.
> Function registration

- .travis.yml
- main/build_mains.sh
> Build mains as part of ci

- main/static/script.js
> Fix tabular display of select metrics in UI

- README.md
> Add license icon

- query/expression.go
- query/function.go
- query/transformation.go
- query/transformation_test.go
> moving_average fetches before timeseries

- main/static/index.html
- main/static/script.js
- main/static/style.css
- ui/ui.go
Updating the front-end.
* extracted out the google chart loading.
* tab -> space for consistency.
* using queries instead of hashes. using HTML5 mode in angular, using
$location instead of depending on window.location.
* some change to the in-flight query detection.
* some change to the label generation logic to use the `name` field.
> Updating the front-end

- main/static/dummy.go
- ui/ui.go
creating static dummy file and importing it, so that `godep` picks these files.
> ensure that the godep includes static files

- main/static/dummy.go
- main/static/script.js
- main/static/style.css
is an empty file copyrightable?
> adding copyright text

- log/glog/logger.go
- log/log.go
- log/standard/logger.go
- main/common/common.go
Allows for debug, info, warning, error, fatal logging with various loggers
> Add logging support

- query/transformation.go
- query/transformation_test.go
> Fix scale to be seconds instead of milliseconds

- internal/api.go
> adding timeout

- api/backend/blueflood/blueflood.go
- log/glog/logger.go
- log/log.go
- main/common/common.go
- main/static/index.html
- main/static/script.js
- main/static/style.css
- main/ui/ui.go
- ui/ui.go
Add a support for profiler.
* added UI to expose the profiler.
* added server-side support.
* abstracted out the google chart integration a bit.
* fixed the logger - using glog by default, passing varargs correctly, etc.
* reduced a lot of logging levels to DEBUG
> Adding profiling UI support

- main/ui/ui.go
- ui/ui.go
adding new endpoint `/token` that returns all the tokens exposed by MQE.
> Jee.20150626.wire up functions

- main/static/autocom.js
- main/static/index.html
- main/static/script.js
- main/static/style.css
Autocomplete only knows about keywords right now (and some of the functions).
> Autocomplete

- internal/cassandra.go
- internal/cassandra_test.go
- schema/schema.cql
- schema/schema_test.cql
> Metric Sets / Caching Describe All

- api/types.go
- api/types_test.go
- function/transform/special.go
- function/value.go
- function/value_test.go
- query/expression.go
- query/language.peg
- query/language.peg.go
- query/node.go
- query/parser.go
- query/query_test.go
The `DurationValue` type represents quantities that are durations. There is no implicit conversion allowed between numbers and duration values.
> Create and use duration type for values

- function/registry/registry.go
- function/transform/transformation.go
- function/transform/transformation_test.go
and removing `checkParameters`
> implementing log function

- EXAMPLES.md
- EXPRESSIONS.md
- FUNCTIONS.md
- function/aggregate/aggregate.go
- function/transform/transformation.go
> Function documentation

- FUNCTIONS.md
Changes the documentation to use tables which are more explanatory and better details the specifics of joining and aggregation.
> Improve documentation clarity for functions

- internal/cassandra.go
- internal/cassandra_test.go
- internal/errors.go
> Error when invalid metric (one with no tags) is requested

- main/static/embed.html
- main/static/index.html
- main/static/script.js
- main/static/style_embed.css
The page `embed.html` will render a graph that fills the screen, using the URL parameters as the query and settings.
An `<iframe>` can link to the embed page for an MQE graph.
The JS was refactored to allow reduced duplication.
Autocom no longer interferes with Angular reading the DOM, so it's been un-hacked.
Autocom configuration parameters have been adjusted slightly.
> Embed Graphs

- main/static/embed.html
- main/static/index.html
- main/static/script.js
- main/static/style_embed.css
- ui/ui.go
* removed scrollbar on embed view.
* pretty URL for the HTML views.
* ability to set titles.
* fix the zero rendering issue.
> A bit of update on UI:

- main/static/autocom.js
- main/static/script.js
First, fixed a mistake that made Autocom non-functional in master (typo).
Second, had to re-hack the integration of Autocom and use `document.getElementById("query-input").value` since modifications of the DOM by Autocom aren't picked up by Angular right away.
> Autocom Integration Fixes

- query/language.peg
- query/language.peg.go
- query/query_test.go
no Scala-like nested comments :)
> Support for SQL-style comments - inline and trailing

- api/backend.go
- function/errors.go
- function/expression.go
- function/expression_test.go
- main/common/common.go
- main/static/index.html
- main/static/style.css
- main/static/style_embed.css
- main/ui/ui.go
- query/command.go
- query/expression.go
- ui/data.go
- ui/ui.go
* added an error type to handle resource-limiting behavior (timeout, fetches, slots, etc)
* removed main/ui/ui.go-specific configs from ui/ui.go
* changed the error to use a monospace font.
* adding `application/json` header.
> Jee.20150713.ui fixes

- internal/rules.go
This is needed to implement linters
> implement introspection to rules

- main/static/embed.html
- main/static/index.html
- main/static/script.js
- main/static/style.css
- main/static/style_embed.css
* resize detection - graphs are re-rendered on window resize.
* pulled out chart rendering to `google-chart` directive.
* reduced angular factory footprint - moved most logic to controllers.
* reduced controller logic duplication by having `commonCtrl`.
> UI improvements

- api/api.go
- internal/api.go
> Switch to config directory for rules

- main/static/index.html
- main/static/script.js
- main/static/style.css
* adding message on # of data rendered.
* filter the data from being displayed if there are too many ( >200) being rendered.
* support for 2nd y axis.
* support for custom color and width of lines.
> Better UI queues

- mocks/api.go
- query/command.go
- query/command_test.go
- query/language.peg
- query/language.peg.go
- query/node.go
- query/parser.go
- query/query_test.go
grammatically, "describe all MATCHING ..." is more correct, but i'm a
bit conflicted - i don't want to have both MATCHES and MATCHING as
keywords.
WDYT?
> Adding "matches" statement

- api/backend/blueflood/blueflood.go
- api/backend/blueflood/blueflood_test.go
- api/timeseries.go
- api/timeseries_test.go
- api/types.go
- api/types_test.go
- function/filter/filter.go
- function/transform/special.go
- function/transform/transformation.go
- main/common/common.go
- main/static/script.js
- main/ui/ui.go
* refactoring the resolution choosing code a bit.
* less hard-coding of resolution choosing code.
* renamed `Timerange.Resolution()` to `ResolutionMillis()`. added `Timerange.Resolution()` which returns the result in `time.Duration`.
> Refactoring resolution choosing code a bit

- internal/api.go
- main/common/common.go
- main/static/script.js
> Set precision of data to 2 decimals in ui

- main/static/embed.html
"See on metrics indexer" => "Explore in MQE"
@Nathan-Fenner @kuzmik
> Change embed link contents

- main/static/embed.html
- main/static/script.js
- main/static/style_embed.css
use `explore=hide`, `legend=hide` to configure the chart display. `explore` only affects the embedded view.
> Add toggles to hide the legend and the "Explore on MQE" label

- main/static/script.js
Will abbreviate 8,000,000 as 8M, etc.
> Use short units along y-axis

- ui/ui.go
> Default to non-indented JSON, allow supplying pretty=true

- util/rules.go
Investigating a bug in MQE suggests that there may be a problem with some part of the graphite => tagged-metric conversion. There is a buggy tendency to introduce NULL and other illegal characters into the strings. This logging should make it straightforward to tell if there is a problem.
> Add logging for possible failure cases

- metric_metadata/cassandra/cassandra.go
- metric_metadata/cassandra/cassandra_test.go
- schema/schema.cql
* schema now uses replication factor of 3
* using quorum on reads is unnecessary
> Fixes from yesterdays outage

- function/registry/registry.go
- function/transform/special.go
> Define exponential moving average function

- query/command.go
- query/inspect_test.go
- ui/ui.go
Adds profiling for parsing and a few other measurements. Minor refactor to make this possible.
@drcapulet
> Add more profiling

- EXPRESSIONS.md
- api/metric_metadata_api.go
- api/types_test.go
- compress/compress.go
- compress/decompress.go
- compress/util.go
- function/aggregate/aggregate_test.go
- function/forecast/anomaly_function.go
- function/transform/special.go
- function/value.go
- main/ui/ui.go
- metric_metadata/cached_metadata/cached.go
- metric_metadata/cassandra/cassandra_api_test.go
- metric_metadata/cassandra/cassandra_db_test.go
- query/command_test.go
- query/expression_test.go
- query/parser.go
- testing_support/mocks/http_client.go
- timeseries_storage/blueflood/blueflood.go
- timeseries_storage/blueflood/blueflood_test.go
- ui/query.go
- ui/query_test.go
> Spelling and golint & gofmt fixups

- .travis.yml
> Start testing on Go 1.6 as well

- log/standard/logger.go
R: @Nathan-Fenner || @DanielNi
> Properly format log messages for the standard logger

- function/transform/special.go
> Fix `transform.alias`

- timeseries/blueflood/blueflood.go
Fixes a bug in profiling Blueflood (so now there will be per-fetch metrics).
@drcapulet
> Profile individual requests

- function/registry/registry.go
- function/transform/transformation.go
- function/transform/transformation_test.go
> Add back transform.nan_fill instead of transform.default

- timeseries/blueflood/blueflood.go
R: @Nathan-Fenner || @DanielNi
> Don't try and parse a non-200 response as JSON

- query/command/command.go
This fixes a minor UI bug in MQE, and possibly broken interface when talking to other services over JSON.
@drcapulet
> don't omit series when empty

- function/registry/registry.go
- function/summary/summary.go
- query/tests/command_select_summary_test.go
This PR adds a few more useful `summarize` functions.
@drcapulet
> Add extra summarize functions

- util/errors.go
- util/rules.go
> Improve ruletester error messages

- function/builtin/transform/special.go
- query/tests/command_select_moving_average_test.go
> Clean up exponential moving average and add tests

- main/ruletester/ruletester.go
- query/parser/node.go
Found with structcheck
@drcapulet
> Remove unused types

- demo/emit/mock.go
- function/builtin/forecast/anomaly_function.go
- function/builtin/forecast/rolling_function.go
- function/builtin/forecast/utility.go
- function/registry/registry_test.go
- main/ruletester/ruletester.go
- metric_metadata/cached/cached.go
- query/command/command.go
- query/expression/expression.go
- testing_support/mocks/api.go
- testing_support/mocks/combo_api.go
- testing_support/mocks/http_client.go
- timeseries/blueflood/blueflood.go
- timeseries/blueflood/plan_intervals.go
This satisfies a golint check.
@drcapulet
> lowercase error messages for better composability

- demo/example-config.yaml
- query/parser/build.sh
- query/parser/error_test.go
- query/parser/language.peg
- query/parser/language.peg.go
- query/parser/node.go
- query/parser/parser.go
- testing_support/script/verify-build
Replace go-peg's errors with useful ones. This requires a lot of additional annotation, and there's still probably some uncaught errors.
@drcapulet
> Better Error Messages

- util/compress/compress.go
- util/compress/compress_test.go
> Fix buggy compression behavior

- main/web/static/autocom.js
Fixes #315 and #316 along with possibly a few other oddities.
> Minor fixes to autocompletion

- main/web/static/autocom.js
- main/web/static/style.css
- Dispatch a new "input" event so that autocomplete actually works
- Explicitly set height of the first tab so autocomplete options are no longer hidden
Still need to fix the broken build...
@syamp @drcapulet
> Autocomplete UI fixes
