square/metrics

- query/aggregate.go
- query/aggregate_test.go
- query/errors.go
This pull request defines and implements aggregator functions which can be used to take a list of timeseries, group them by their tags, and then combine each group into a single timeseries using an aggregator like their sum, minimum, maximum, or mean.
`func aggregateBy(list api.SeriesList, aggregator func([]float64) float64, tags []string) (api.SeriesList, error)` is the API for access by the rest of the query system, along with the aggregator struct types `sumAggregator`, `meanAggregator`, `maxAggregator`, and `minAggregator`.
> Aggregation Function Implementation

- api/types.go
- query/expression.go
- query/expression_test.go
To better enable string and scalar parameters to functions, `Expression`s return a `Value` interface type instead of always returning `*api.SeriesList`. The `Value` interface defines methods to cast (with possible error returned) to `api.SeriesList`, `string`, or `float64`. There are three instances of the `Value` interface defined, one for each type. Each can only be casted to its own value, except for `ScalarValue` which can produce an `api.SeriesList`.
This change required modifying the corresponding test file to work with the new types.
> Refactor expressions to return Value instead of *api.SeriesList

- query/language.peg
- query/language.peg.go
- query/parser.go
This PR changes several behaviors about string literal parsing:
* String literals now return their contents. Writing `STRING { fmt.printf("%s", buffer[start:end]) }` will now print `Hello!` when parsing the string `"Hello!"` or `'Hello!`' (rather than including the quotes in the output).
* Also, different quotes don't need to be escaped. `"These 'single quotes' don't need to be escaped"` will be parsed correctly (no backslashes needed).
* You'd still need to write `'These \'single quotes\' do need backslashes'` since they match. Also, unfortunately, the resulting string will contain the backslashes, which means that code may need to check for their presence/absence.
> String literal parsing improvements

- api/types.go
- api/types_test.go
- query/aggregate/aggregate_test.go
- query/transformation.go
- query/transformation_test.go
The interface is:
`func ApplyTransformation(list api.SeriesList, transform transform, parameters []value) (api.SeriesList, error)`
Where `parameters` are `value`s representing things like flags, modes, or durations (and correspond to all arguments after the first in the query)
The type `transform` is a synonym for the more verbose:
`func([]float64, []value, api.Timerange) ([]float64, error)`
The following transformations have been implemented: `transformDerivative`, `transformIntegral`, `transformRate`, `transformCumulative`, and `transformMovingAverage`.
Also implemented is `transformMapMaker` which maps a simple scalar functio `func(float64) float64` over the timeseries. The transform corresponding to taking the absolute value, for example, would be `transformMapMaker(math.Abs)`. …
> Transformation function implementation

- api/types.go
- api/types_test.go
- query/expression.go
This PR adds a special case for `timeshift` as a function to be invoked by expressions. It works by modifying the evaluation context before evaluating its first argument.
Currently, timeshifting is a special case, since no other function or operation during expression evaluation actually changes the `EvaluationContext`.
> Add timeshift function

- api/backend/blueflood/blueflood.go
- api/backend/blueflood/blueflood_test.go
- api/types.go
- api/types_test.go
- main/common/common.go
- main/query.go
- main/ruletester.go
- query/aggregate/aggregate_test.go
- query/command.go
- query/command_test.go
- query/expression.go
- query/expression_test.go
- query/join_test.go
- query/node.go
- query/parser.go
- query/parser_test.go
- query/transformation.go
- query/transformation_test.go
This commit un-exports the fields `start`, `end`, and `resolution` from `api.Timerange`. To read them, the methods `.Start()`, `.End()`, and `.Resolution()` are provided.
To construct a new timerange, invoke `api.NewTimerange(start, end, resolution)` which returns `(api.Timerange, error)`.
All instances of `api.Timerange{ ... }` have been replaced with a call to `api.NewTimerange(...)` or `api.DefaultTimerange()` so that all instantiated timeranges are valid, even if they're never used.
To create a valid default timerange, you can call `api.DefaultTimerange()` which gives a timerange corresponding to `{0, 0, 30}`. 
It's still possible to construct an invalid timerange, namely the "zero" timerange `api.Timerange{}`. This behavior is nowhere used (they have all been replaced with …
> Unexport fields from api.Timerange and Standardize Milliseconds

- api/backend.go
- api/backend/blueflood/blueflood.go
- api/backend/blueflood/blueflood_test.go
- main/query.go
- query/command.go
- query/command_test.go
- query/expression.go
- query/expression_test.go
* Backend used to have a reference to API, but this is now removed.
* Making Backend.Fetch()'s arguments into a single object - this allows
us to add more parameters in future with ease.
* Refactoring the backend to not have API() endpoint.
* Refactoring EvaluationContext to have an API field.
* Refactoring Command to have API as an argument.
> Refactoring backend, command, and API

- api/backend/blueflood/blueflood.go
- api/backend/blueflood/blueflood_test.go
Fills in missing data with `NaN`, so that all response series have `len(Values) == timerange.Slots()`. Also combines things with buckets if there's more than one datapoint returned for a given interval.
> Fill in timeseries with NaN for missing data (Blueflood backend)

- query/aggregate/aggregate.go
- query/aggregate/aggregate_test.go
Missing data will be ignored during aggregation. For example, if asked to aggregate 5 timeseries (at some particular time `t`), and the values are `{1, 3, 0, NaN, 6}`, the resulting value will be `10.0/4 = 2.5`. If all values are missing `{NaN, NaN, NaN, NaN, NaN}` then the aggregate result will also be `NaN`.
> Aggregators handle missing data (by ignoring NaNs)

- api/backend.go
- api/backend/multibackend.go
- main/query.go
- query/command.go
- query/command_test.go
- query/expression.go
- query/expression_test.go
- ui/ui.go
A `Backend` has only a `FetchSingleSeries` method, while a `MultiBackend` has only a `FetchMultipleSeries` method. 
There are two `MultiBackend`s defined (both in `api/backend/multibackend.go`). There are `SequentialMultiBackend` and `ParallelMultiBackend`. Both take a `Backend` as a field which they use for performing fetches.
The `ParallelMultiBackend` should be constructed using the `NewParallelMultiBackend( )` function which takes a `Backend` and a `limit` (for maximum number of simultaneous fetches).
Everywhere that previously used a `Backend` now uses `MultiBackend`, using `SequentialMultiBackend` wherever needed.
There are no tests unit tests for these multibackends (only integrations with existing backends) and no tests for the `ParallelMultiBackend` at all.
> Parallel fetch with refactor to use "MultiBackend."

- main/ui.go
- ui/ui.go
This change means that only one `MultiBackend` is created for the duration of a life of the program, rather than one per command.
> Move multibackend instantiation into main/ui.go out of ui/ui.go

- .travis.yml
It's not being used, and it broke a build on another branch.
> Remove golint dependency

- api/types.go
> update the comments

- api/backend.go
- api/backend/blueflood/blueflood.go
- api/backend/blueflood/blueflood_test.go
- api/predicate.go
- api/types.go
This will allow us (in future) to act against different errors.
* implement blueflood to use these error codes.
* refactor blueflood to not expose these fields.
@alexc @Nathan-Fenner
> Better structured backend error codes.

- main/query.go
- main/ui.go
- query/command.go
- query/command_test.go
- query/expression.go
- query/expression_test.go
- ui/ui.go
An `ExecutionContext` type has been created which replaces the `(API, MultiBackend)` passed to each `.Execute(...)` call.
Before a fetch is performed, the number available is checked against the number of series desired. If not enough are available, the metric fetching expression returns an error.
> Limit the number of fetches

- query/expression.go
- query/filter.go
- query/function.go
This PR is based on #95 and adds on the definition of several "filtering" functions, which limit the number of returned Timeseries.
#95 should be finalized before this branch.
> Implement Filter Functions

- query/command_test.go
- query/expression.go
- query/function.go
- query/value.go
A serieslist produced by evaluation now has a proper name, based on the functions which evaluated it.
For example, `select aggregate.sum(cpu group by 'app')` will have a name like `"aggregate.sum(cpu group by app)"`
> Functions compute names

- main/query.go
- main/ui.go
- query/command_test.go
- query/language.peg
- query/language.peg.go
- query/parser.go
- query/parser_test.go
- query/query_test.go
- query/value.go
- query/value_test.go
When using relative dates with `parseDate` (which now asks for a `now` time), the format is identical to `parseDuration`:
The units supported are `s`, `m`, `h`, `hr`, `d`, `w` (week = 7 days), `M`, `mo`, (month = 30 days), `y`, `yr`, (year = 365 days).
> Unify durations 

- query/language.peg
- query/language.peg.go
- query/query_test.go
The basic strategy is as follows:
"Non-terminals" (which are roughly any rule in all-caps or a string literal) will be preceded (whenever they expect one) by an `_` whose rule is still just `SPACE*`.
Any keyword, where appearing as a string literal (e.g., `"select"` or `"where"`) must be followed by the `KEY` rule, which is just `!ID_CONT` (or `![a-zA-Z0-9]`).
For example:
```describeMetrics <- _ "metrics" KEY _ "where" KEY tagName _ "=" literalString { p.makeDescribeMetrics() }```
Since we have a keyword `"metrics"`, it is followed by `KEY`. However, it needs to take care of spaces that may precede it. It doesn't have to take care of spaces that appear after it. Similarly consider the `"="` which has a `_` preceding it. Since it's not a keyword (it's nonalphanumeric) there's no `KEY` …
> Change parsing rules to prevent syntax errors

- query/expression.go
- query/transformation.go
- query/transformation_test.go
The function `transform.nan_keep_last` replaces any `NaN` with the first non-`NaN` that came before (unless there are none, in which case it stays `NaN`).
> Define transform.nan_keep_last

- query/command_test.go
- query/language.peg
- query/language.peg.go
- query/parser.go
- query/query_test.go
Adds a new syntax `expr | func(...args group by y)`, which is
a different way of writing `func(expr, ...args group by y`
```
select
`jvm.thread-count` | aggregate.max | transform.moving_average('2h')
where
type = 'thread_count' and
app in ('esperanto', 'eero', 'ledger')
from -24h to now resolution 5m
```
> Language support for "pipeline" style function application:

- assert/assert.go
- query/aggregate/aggregate.go
- query/filter.go
- query/filter_test.go
The main issues with filtering are due to (1) inconsistent/confusing behavior for totally missing series (all NaN) and (2) the aggregating functions failed whenever a single entry in their argument arrays was NaN.
This PR moves the not-NaN filter from the `applyAggregate` function into each one of the aggregators, so that they can be used as useful summarizes for `FilterBy`.
The tests don't cover expression evaluation directly but do cover the functionality of `FilterBy()` which is used by expressions registered as filters.
`FilterBy`'s argument "`ascending`" has been renamed to the more-clear "`lowest`" meaning that when `true`, it will return the `N` lowest results (if false, it returns the `N` highest). [This change doesn't effect behavior in calling the function].
> Fixing Filter + Filter Tests

- api/api.go
- api/backend.go
- api/backend/blueflood/blueflood_test.go
- inspect/profile.go
- inspect/profile_test.go
- main/ui/ui.go
- query/command.go
- query/command_test.go
- query/expression.go
- query/expression_test.go
- query/inspect_test.go
- query/parser.go
- ui/ui.go
`EvaluationContext` and `Fetch*Request` are given a `Profiler` field of type `*inspect.Profiler` which collects metrics about the evaluation of each command.
The interface for the `Profiler` is a method `func (p *Profiler) Add(name string) func()` which returns a function that adds a profiling metric from the whose `start` is the time of the first call, and whose `finish` is the time of the returned function's call, storing it in `name`.
Typical usage is: 
```
defer request.Profiler.Add("FetchSingleRequest")
```
There is no need to check for a `nil` pointer before doing this call. If the pointer is `nil`, the `.Add` method has no effect.
If it's necessary to time a function that is invoked (rather than modifying the function to do the profiling itself), then you can do the following (for …
> Collect data in Profilers stored in Contexts

- inspect/profile.go
- inspect/profile_test.go
Adding the `Flush()` method - this is used to ensure that we can use `ProfilingAPI` in square's codebase to profile `API` that is not part of command - i.e. kafka consumers inserting metrics.
> adding profiler.flush

- function/aggregate/aggregate.go
- function/aggregate/aggregate_test.go
- function/expression.go
- function/filter/filter.go
- function/filter/filter_test.go
- function/join/join.go
- function/join/join_test.go
- function/value.go
- function/value_test.go
- query/command.go
- query/command_test.go
- query/expression.go
- query/expression_test.go
- query/function.go
- query/node.go
- query/parser.go
- query/transformation.go
- query/transformation_test.go
This is part 1 - I got sick of doing this work - so i'm putting it here.
value, expression, and EvaluationContext are all pulled out to `function` class - it mostly contains types & aggregate functions that are used by functions. Next todo items are:
* pulling transformations out (not hard, but tests have some dependency on nodes).
* pulling function registration out.
> Part 1 of extracting function out of `query`

- assert/assert.go
- function/aggregate/aggregate.go
- function/aggregate/aggregate_test.go
- function/registry/registry.go
- function/transform/transformation.go
- function/transform/transformation_test.go
* `aggregate.total` tells how many timeseries are in the serieslist (or group)
* `aggregate.count` tells us how many values aren't `NaN`
* `transform.bound(low, high)` lets us place bounds on functions (they'll be clamped to the edges)
* `transform.lower_bound(low)` lets us place a lower bound
* `transform.upper_bound(high)` lets us place a higher bound
Also fixes a bug in `assert.EqFloatArray` (sign of `delta` was being ignored, so some differences would have gone unnoticed. No tests failed after correcting this behavior).
> More Functions - Bounding transforms and counting aggregates

- query/language.peg
- query/language.peg.go
- query/query_test.go
Requiring `KEY` to follow the duration suffix is necessary to parse everything correctly.
> Fix bug in parsing duration literals

- function/aggregate/aggregate.go
- function/aggregate/aggregate_test.go
- function/expression.go
- function/registry/registry.go
- function/registry/registry_test.go
- function/transform/special.go
- query/command_test.go
- query/expression.go
- query/expression_test.go
- query/language.peg
- query/language.peg.go
- query/node.go
- query/parser.go
- query/query_test.go
The `combine by` clause acts oppositely to the `group by` clause.
Performing `cpu | aggregate.sum( collapse by host )` will eliminate the `host` tag by ignoring the host tag while aggregating - so series which are otherwise the same but with different hosts will be aggregated.
TODO: *integration* tests for collapse
> Define 'collapse by' clause

- query/parser.go
`AssertionError`s won't show up when the user makes a syntax error in numbers or durations.
(They will instead receive a proper `SyntaxError` message instead of "Programming error")
> Assertion Error Fix

- function/filter/filter.go
- function/filter/filter_test.go
- function/registry/registry.go
- query/command_test.go
This PR defines a series of functions `filter.recent_*` which act similarly to `filter.*`.
Their purpose is to filter based on recent activity, rather than on total activity. For example:
`select filter.recent_highest_max( cpu, 5, 1d ) from -2w to now`
will show CPU usage for 5 hosts over the past 2 weeks, choosing these hosts by their activity only in the last day.
> FilterRecent

- function/registry/registry.go
- function/tag/tag.go
- function/tag/tag_test.go
- query/command_test.go
Defines two new functions:
`tag.drop(serieslist, tag)` which will remove the tag from all series.
`tag.set(serieslist, tag, value)` which sets the tag for all series.
> Tag Functions (Drop / Set)

- main/static/autocom.js
- main/static/script.js
Fixes existing undesirable behavior in Autocom.
* Add a feature to penalize long candidate words (so shorter candidates will be suggested first)
* Add a feature so that autocomplete suggestions won't appear in the middle of words before special characters
> Tweak autocompleter to be easier to use

- FUNCTIONS.md
- function/registry/registry.go
Documentation adds examples (with tables) to the documentation for transformation functions.
> Add elaborative examples to transformation function documentation

- query/command.go
- query/command_test.go
This allows you to graph (for example):
`select cpu, 100 from -10m to now` to get a straight line at 100. Certain queries, like `select 'string' from -10m to now` will now error (failing to convert string => series list) instead of silently succeeding with a useless result.
> Select coerces results to type SeriesList

- function/transform/special.go
- function/transform/transformation.go
- function/value.go
- query/command_test.go
- query/expression.go
- query/node.go
- query/parser.go
- query/transformation_test.go
Errors are made somewhat more structured.
* Instances of `errors.New()` are replaced by typed implementing the `ExecutionError` interface (which also has a `.TokenName()`).
* String => Duration implicit casts are no longer allowed. This causes errors to have closer to parsing, rather than execution, and makes the language more consistent. Strings are now only used to refer to tag values (or tags keys with `tag.drop`/`tag.set`) and absolute timestamps.
> Rework errors and durations

- query/parser.go
- query/query_test.go
* Removed ANSI formatting.
* Instead of just printing out the substring where the error has occurred, the entire line is printed (with cursors under it).
* remove duplicate errors & unknown errors (reduce the noise level a bit).
a sample error looks like this:
```
query_test.go:201: parse error near [ID_START] (line 2 symbol 9 - line 2 symbol 10):
where key matches 'ab' from 0 to 0
^
parse error near [ID_SEGMENT] (line 2 symbol 7 - line 2 symbol 10):
where key matches 'ab' from 0 to 0
^^^
parse error near [CHAR] (line 2 symbol 21 - line 2 symbol 22):
where key matches 'ab' from 0 to 0
^
parse error near [QUOTE_SINGLE] (line 2 symbol 22 - line 2 symbol 23):
where key matches 'ab' from 0 to 0
^
parse error near [Action44] (line 2 symbol 23 - line 2 symbol 23):
where key matches 'ab' from 0 …
```
> better syntax error

- main/static/index.html
- main/static/script.js
- main/static/style.css
This PR adds HTML/JS/CSS for a query history box at the right side of the query window.
The first few characters of every query can be seen - hovering over the box shows the remainder. Clicking on a row fills the input area with that query.
Also, fixed issues with legend appearance + made the chart larger (vertically)
> Query history shown in right column

- main/static/index.html
- main/static/script.js
- main/static/style.css
- query/command.go
- query/command_test.go
Instead of listing every tagset for a given metric, the server computes a `map[string] []string` that it sends to the client, mapping each `key` to a list of associated `value`s.
The results are displayed in a series of tables (`display: inline-block; float: left`) with a small margin between them.
> Short, tabular display for 'describe' queries

- query/command.go
- query/command_test.go
Default: 1000 slots (8.3 hours at 30s resolution).
It can be configured through the `ExecutionContext`.
Note: this is only based on the original query for timeseries.
* Asking for many expressions: `select X, X, X, X, X, X, X, X, X, X, X, X, X, X, X, X, X, X from -8h to now` will select and return 17280 points
* `transform.moving_average` expands the search range, so `select transform.moving_average(X, 10d) from -1h to now` will select 28000 points of data, but only return the last 120 of these.
> Add configurable limit on resolution slots

- function/expression.go
- function/registry/registry.go
- query/command.go
- query/expression.go
There are few cases where we want to evaluate subexpressions in
parallel. This PR abstracts out that logic so that it can be used in
different places, including:
* binary operators.
* top-level command evaluation.
> Implementing a parallel execute

- query/command.go
- query/natural_sort/natural.go
- query/natural_sort/natural_test.go
Defining this is a bit ridiculous. The point is to provide a better sorting experience for users. Lexicographical sorting (with ASCII order) isn't really what a human would expect. For example:
Apple < Zoo < apple < file100 < file2 < file90 < file99 < zoo
This package `natural_sort` defines a function `natural_sort.Sort(array []string)` that sorts its arguments in a natural order:
Apple < apple < file2 < file90 < file99 < file100 < Zoo < zoo
For reference, see:
https://en.wikipedia.org/wiki/Natural_sort_order
http://blog.codinghorror.com/sorting-for-humans-natural-sort-order/
> Natural Sort for Strings

- query/parser.go
- query/query_test.go
if a syntax error occurs end-of-line, then it used to cause the parser to panic
> fixing parser syntax error panic

- EXPRESSIONS.md
- api/types.go
- function/registry/registry.go
- function/tag/tag.go
- function/transform/special.go
- function/value.go
- query/expression.go
- query/expression_test.go
Instead of making a wrapper type in the `function` package, it is much
simpler to implement the type methods in the `api` package. Otherwise,
we have to ensure that all implementing functions need to cast the
result to SeriesListValue.
> Remove SeriesListValue for simplicity

- main/static/embed.html
- main/static/style_embed.css
Only 200 series are ever shown, even if more are returned. This is true on both the main UI view and the embedded view.
However, when the limit is enforced, the main UI view got a message, while the embedded view did not.
This PR adds a notice to embedded views when there are more than 200 series (but only the 200 are shown).
Before:
After:
> Add warning on embed UI when series limit is reached

- main/static/index.html
- main/static/style.css
When there were lots of tags, the columns would layout in a way that was very difficult to read and understand.
This change places the columns from a `describe ...` query into a box of fixed maximum size, showing scrollbars when its contents can't all be shown at once.
> Change layout for describe

- main/static/autocom.js
When there are a lot of alternatives, the autcomplete performance starts to suffer. Adding a cache should help this a little bit.
Some related changes were made to how shift behavior works (now shift+arrows will suppress the tooltip, but not shift+letter which made it impossible to autocomplete things with capital letters).
> Improvement to Autocomplete Performance

- main/static/script.js
- main/static/style_embed.css
Previously, the percentage-based chart areas meant that there'd be excessive or insufficient margins around charts depending on their size.
This PR allows `chartArea` to be given as left: right: top: bottom: in pixels, rather than left: top: width: height: in percents.
It's configurable by adding the URL parameters `marginleft`, `marginright`, `margintop`, or `marginbottom` as either percentages or pixels (such as `marginleft=50%25` or `marginleft=15px`)
> Pixel-based margins for chart area

- api/backend/blueflood/blueflood.go
- api/backend/blueflood/blueflood_test.go
- query/language.peg.go
Full resolution data (roughly 30s resolution) is usually available immediately. However, it takes a while for rollups to be performed and therefore lower resolution data (5m, 1hr, 1day) may not be available for a while.
This PR adds a feature to fetch full-resolution data to fill this gap in data. The last 4hrs (configurable) of the requested timerange is also fetched from full resolution data. They're combined when bucketing.
Since the full-resolution data should be sampled down in the same way that rollups are performed, it will look like the regular data is fully available. 
This essentially doubles the number of fetches required, although the number of points returned is not likely doubled.
> Fill in lower-resolution data with full resolution data

- main/static/embed.html
- main/static/index.html
- main/static/script.js
- main/static/style_embed.css
Previously there was no good indicator that no series were returned. Now there is.
An error will show for both the UI view and the embed view.
If you do a query with multiple expressions (ie `select X, Y from -10m to now`) then if either `X` or `Y` result in 0 expressions, the error will be shown. 
> Show error when 0 series are returned

- api/types.go
- function/aggregate/aggregate.go
- function/aggregate/aggregate_test.go
- function/join/join_test.go
- function/registry/registry.go
- function/tag/tag.go
- function/transform/special.go
- function/transform/transformation.go
- query/command_test.go
- query/expression.go
- query/expression_test.go
This introduces a new field on `SeriesList` named `Query` that has the full query for the given TimeSeries. This will be the same as `Name` unless `transform.alias` is used.
> Expose the full query even if an alias was used

- api/api.go
- internal/api.go
- internal/cassandra.go
- internal/cassandra_test.go
- mocks/api.go
- query/inspect_test.go
This adds a simpler bulk add metrics API for cassandra that does streaming. Doesn't look like the go cassandra driver supports the same level of streaming large inserts that the Java/C# driver does (https://medium.com/@foundev/cassandra-batch-loading-without-the-batch-keyword-40f00e35e23e). I could be wrong. Either way this is about as fast as I can get it without relying on more clever methods.
I'm also removing the caching from the cassandra code in favor of moving it higher up into the stack.
> Add bulk add Metrics API and remove db-specific caching.

- build_verify.sh
- metric_metadata/cassandra/cassandra_test.go
- query/command_test.go
This addresses two separate timeouts that I saw happen in CI builds yesterday. I ran over 80 builds and only had 2 show up.
I also ran the tests in a loop on my laptop, and in 542 runs there were 0 timeouts; so it is clearly something a bit weird with travis. Hopefully this does something to alleviate SOME of the pain.
> Kuzmik testing ci

- function/registry/registry.go
- function/transform/special.go
- function/transform/transformation.go
- function/transform/transformation_test.go
The transform.rate and transform.derivative functions now fetch an extra point
before the start of the timerange so that the start of the timerange represents
the delta from the point before, not simply 0.
The transform.integral and transform.cumulative functions now always start at
zero since the left-most datapoint isn't technically part of the series we're
summing or integrating over.
R: @cchandler || @cuzelac
> Calculate full timeranges for rates & derivatives, change Integral & Cumulative

- .gitignore
- main/ruletester/ruletester.go
- util/graphite_converter.go
- util/rules.go
- util/rules_test.go
I've modified the old ruletester file to be able to read the new zlib compressed gob encoded cache file we generate from the metrics-indexer upstream. Yes, the ruletester file is a bit of a mess right now, but I think that's fine. We need to refine this and get more data out of it most likely, so I'm leaving it there for now for the next person :-).
I've also exported a lot of the data from the util.GraphiteConverter stuff so we can get per-rule statistics from within the converter itself. There's probably more we want to track.
> Build txt file reports from what matches and what doesn't

- api/metric_metadata_api.go
- api/timeseries_storage_api.go
- function/expression.go
- main/metadata/metadata.go
- main/ruletester/ruletester.go
- metric_metadata/cassandra/cassandra.go
- query/command.go
- query/command_test.go
- query/expression.go
- query/inspect_test.go
- query/transformation_test.go
- testing_support/mocks/api.go
- timeseries_storage/blueflood/blueflood.go
- timeseries_storage/blueflood/blueflood_test.go
- ui/ui.go
This PR fixes profiling in MQE. See #206 as well, which offers a different solution.
In this version, the `*inspect.Profiler` pointers are carried by the `ExecutionContext` and the `EvaluationContext`, and added to the `FetchTimeseriesRequest` and `FetchMultipleTimeseriesRequest` when they are created. The `*Profiler` for the `MetricMetadataAPI` is placed into a `MetricMetadataAPIContext` which is added as an argument to every call. Currently, it's simplest created by putting the `*Profiler` from the execution context or the evaluation context into it.
Each MetadataAPI and TimeseriesStorageAPI implementation is responsible for performing its own profiling- there's no longer any kind of `ProfilingFooAPI`. 
~~The main advantage of #207 over #206 is that you're able to get profiling data …
> Fix Profiler - Delete ProfilingAPI types

- main/common/common.go
- main/ruletester/ruletester.go
While trying out the new ruletester, I ran into a few problems that were pretty straightforward to solve:
* When a flag is missing, say what flag it is: namely `-metrics-file` and `-rule-path`
* Don't ask for a complete configuration file (doesn't need `-config-file`)- only the conversion rule path was being used, so the rest of the config was extraneous
* Increase `runtime.GOMAXPROCS` to `runtime.NumCPU()` so that it runs fully in parallel - this increased speed slightly on my machine
I also just cleaned up the commented code and some unused functions, and added error checking in a handful of places.
The batching of metrics obscured what was going on in the code a little bit- so I got rid of it. Running the program a few times on my machine took ~65s (real/clock time) either way.
To help …
> Ruletester Cleanup / Usability Improvements

- function/expression.go
- main/ui/ui.go
- optimize/optimize.go
- optimize/optimize_test.go
- query/command.go
- query/command_test.go
- query/expression.go
- query/inspect_test.go
- query/transformation_test.go
The optimize functions are external to both query/function because
go forbids import loops and the capabilities have to be available
in both. Further, I'd like this to be as implementation agnostic
as possible since it's technically for query optimization, so I
opted to put it in its own package for now rather than push it into
the underlying metricmetadata API
> Add an externalized optimizer.

- query/command.go
- query/command_test.go
- query/inspect_test.go
- query/transformation_test.go
- testing_support/mocks/api.go
Previously, when a timeout was specified, `select` actually behaved slightly differently than when it was not. In particular, it apparently bypassed checks that the resulting expressions were serieslists.
This PR unifies the approach taken when a timeout is present and when it is absent. Because of this, when the timeout is not specified, one additional goroutine is spawned for the duration of the request than previously existed.
Also, there was a small potential for a very gradual leak. Go does *not* garbage collect goroutines, and sending on a channel with default capacity (0) will block until a receiver comes along. In the event of a timeout, the goroutine that was launched to evaluate the expression was never able to finish, so it would hang onto the memory for its channels and …
> Cleanup for select queries and fixes to tests and mocks

- query/command.go
A typo was introduced in the timerange selection code for executing `select` commands.
This caused MQE to ignore the slot limit and the API-specified best resolution.
This PR fixes the typo and renames the involved variables to improve clarity.
> Fix typo in timerange selection

- optimize/optimize.go
This PR locks the cache mutex before reading from the `metricsKeyToTagCache` map.
Maps in Go are not threadsafe. It is only safe for there to be *one writer* **or** *many readers* **but not both**.
If a goroutine writes to the map while another goroutine is reading it, garbage may be read from it.
> Fix race condition in metric tag caching

- function/expression.go
- function/expression_test.go
- function/registry/registry.go
- function/registry/registry_test.go
- function/tag/tag.go
- function/transform/special.go
- function/transform/transformation.go
- function/transform/transformation_test.go
- query/command.go
- query/expression.go
- query/expression_test.go
- query/transformation_test.go
This modifies the usage of EvaluationContext to include EvaluationNotes during function evaluation. Now that it passes a pointer around please be careful with copy semantics :-).
Example:
The non-negative derivative functionality now creates a context note like this:
ctx.AddNote(fmt.Sprintf("Rate(%v): The underlying counter reset between %f, %f\n", series.TagSet, values[i-1], values[i]))
This passes information back to the UI that wouldn't be obvious from the processed numbers alone. It will include things like strange rounding, empty data buckets, unexpected nils, interpolation, whatever.
It also changes the signature of the transform function type to work directly on api.Timeseries instead of a simplified, contextless []float64.
A few TODOs were added that I'll address later this week. …
> Context notes on function evaluation

- main/query/query.go
- query/command.go
- query/command_test.go
- ui/data.go
- ui/ui.go
As a way to address issue https://github.com/square/metrics/issues/214 adds a `metadata` field to the JSON response from MQE.
The metadata map can contain information that is secondary to the result itself. Implemented here are descriptions for `select` queries (the tagsets of the resulting series are combined) and profiling information. (To maintain reverse compatibility, the original `.profile` field is still available in the JSON response, but now it is *also* available through `.metadata.profile` which will allow us to eventually move to a state where profiling information is not quite as privileged in that sense).
> Add metadata to command execution results

- api/types.go
- inspect/profile.go
- main/static/script.js
- main/ui/ui.go
- query/command.go
- timeseries_storage/blueflood/blueflood.go
- ui/data.go
- ui/ui.go
This will add evaluation notes to the metadata response. It also now uniquely identifies FetchSingle requests in the response.
> Add notes to metadata return and improve profiling result for blueflood

- api/timeseries.go
- api/timeseries_storage_api.go
- api/timeseries_test.go
- function/expression.go
- function/join/join_test.go
- function/registry/registry.go
- function/value.go
- main/ui/ui.go
- query/command.go
- query/command_test.go
- query/expression.go
- query/expression_test.go
- testing_support/mocks/api.go
- timeseries_storage/blueflood/blueflood.go
- timeseries_storage/blueflood/blueflood_test.go
- ui/ui.go
I've added a flag on the query string called 'raw'. If set to true it will base64 all the original payload results from the underlying TimeseriesStorageAPI onto the response body. Testing this week has revealed several cases in which I wished I had direct access to the underlying data.
I'll add some tests in the morning.
> Include raw payload

- main/ruletester/ruletester.go
- util/graphite_converter.go
- util/rules.go
Adding a bit more information to the ruletester makes it easier to diagnose some problems.
The report files contain the full metric name from source, instead of the regex, and also list the file that the conversion rule comes from.
> Add some new features to the ruletester

- util/rules.go
- util/rules_test.go
This allows you to exclude certain metrics from a conversion rule by rejecting the match if the result's tag values match their `do_not_match` field.
Golang does not support negative lookahead in its regular expression (in order to keep them more regular, as well as to ensure O(n) matching) and therefore it can be very difficult to intentionally exclude certain metrics from being matched.
It used to be that metrics were just matched in order, so that you could exclude from one rule by matching with another. However, because of danger of this introducing subtle bugs when one rule was changed, the behavior was changed so that order must not matter, and all metrics should match at most one rule.
This change makes it possible to easily exclude metrics from a particular rule, while keeping it …
> Add `does_not_match` field to conversion rules

- util/rules.go
- util/rules_test.go
Previously, the checks were only done in the forward direction. Now they are done in both.
> Exclude metrics based on exclusion regexes when converting to graphite names

- .gitignore
- compress/compress.go
- compress/compress_test.go
- compress/decompress.go
- compress/util.go
- main/compressor/compressor.go
I took a few hours and wrote a sample implementation of the streaming XOR-based compression algorithm that Facebook vaguely discusses in their Gorilla paper. Initial experimentation reveals that it has pretty good performance characteristics. The code is a little rough in parts, but it has several test vectors.
A possible future direction (especially for larger slabs) would be to implement a different version that uses the differential-finite-context-method predictor enhancements discussed in "Fast Lossless Compression of Scientific Floating-Point Data" by Paruj Ratanaworabhan, Jian Ke, and Martin Burtscher. If I'm reading it right it sounds like they save the prediction table (at least in part) but it might lead to better space saving overall.
> Implements XOR-based float64 slice compression

- function/transform/special.go
- function/transform/transformation_test.go
Fixes a bug when using `transform.rate`.
Downsampling can cause sudden drops to be smeared out over several slots in the timeseries. The result was mis-reporting many resets over the interval of time that the downsampling occurred.
Since the resets were only partial, the values looked really, really large for long-running counters, and, consequently, caused enormous spikes.
This change requires that the next point show an increase (in addition to decreasing from the previous) to be considered a reset.
> Bugfix for transform.rate

- metric_metadata/cassandra/cassandra.go
- timeseries_storage/blueflood/blueflood.go
Previously, calls to `AddMetrics` in the Cassandra API instances always returned `nil` to indicate error, even if there was an error. This was because they didn't actually check errors returned by query execution, for example.
This pull request adds error checking. It also fixes a very small space leak which would cause some goroutines to hang forever in the event of a query timeout.
> Add errors to AddMetrics calls for Cassandra API

- metric_metadata/cassandra/cassandra.go
- metric_metadata/cassandra/cassandra_api_test.go
- metric_metadata/cassandra/cassandra_db_test.go
- metric_metadata/cassandra/cassandra_test.go
In the transition from using `AddMetric` to `AddMetrics` in the Cassandra API, it was forgotten to include the tag-key indexing inserts.
This PR allows you to use the query `describe metrics where key = 'value'` when indexing with `.AddMetrics`.
> Add support for metric tag-key indexing

- api/serieslist.go
- function/expression.go
- function/forecast/anomaly_function.go
- function/registry/registry.go
- function/tag/tag.go
- function/transform/special.go
- function/transform/transformation.go
- function/value.go
- query/command.go
- query/expression_test.go
- query/transformation_test.go
When a type conversion error occurs, now the query that produced the value with the wrong type is printed, instead of the value itself.
This mainly serves to fix the issue associated with removing names from SeriesLists- now when you accidentally use a serieslist as a (say) duration, the invalid argument will be identified by name in the error.
@drcapulet
> Add messages describing the source of type conversion errors

- query/command_names_test.go
- query/node.go
- query/predicate.go
A recent change which allowed the query labels to correctly escape their contents was overzealous. In particulae, `foo.bar` would always be escaped because of the `.`, even though this is a legal identifier.
This PR updates the identifier regex used in escaping to reflect this, and updates the tests to correct this oversight.
@drcapulet
> Remove unnecesarry escaping for names with dots

- query/parser.go
- query/parser_test.go
In anticipation of https://github.com/square/metrics/pull/233, removes the restriction that relative fetches (`from -1d to now`) must be in the past. So you can now write `from now to +3d`
> Remove checks for future queries

- api/timeseries_storage_api.go
- demo/conversion_rules/cpu.yaml
- demo/conversion_rules/http.yaml
- demo/emit/mock.go
- demo/emit/source.go
- demo/example-config.yaml
- demo/ingest/ingest.go
- timeseries_storage/blueflood/blueflood.go
This PR makes it easier to start up a local instance of MQE and start indexing metrics.
`/demo/emit` has a program which emits sample metric data over HTTP to a Blueflood instance and to a metric indexe.r
`/demo/ingest` has a program which collects metric metdata over an HTTP endpoint and stores the metsdata in a cassandra instance,
The `/demo/conversion_rules` has conversion rules for the demo metrics.
The `/demo/example-config.yaml` file has an example of a configuration file to start the MQE UI.
Detailed documentation for starting and using the server will be made available on the GitHub Wiki for this project.
@cchandler @drcapulet @syamp
> Demo data and conversion rules

- main/static/autocom.js
- main/static/script.js
If a user has something like
```
`cpu.percent`^
```
where the `^` is the cursor, and press enter they get
```
cpu.percent^
```
instead of what they (probably) expect,
```
`cpu.percent`
^
```
This PR fixes this issue.
In addition, it offers a slight performance improvement when there's a large number of options, by calling the autocompletion function about 3x less.
@drcapulet 
(Tested locally)
> Add 'tolerate' feature to autocom

- main/static/autocom.js
- main/static/script.js
Namely, the use of `where` or `from` or `to` or `resolution` or `sample` will cause it to stop suggesting metric names or functions to fill in.
It's slightly brittle, since it's just looking for `\swhere\s` (which can appear in backquoted metrics, for example) or can fail to be detected because of something like `)where`...
In either case, losing (or keeping) autocomplete support is not the end of the world. Fixing this issue in all cases would require a complete parser for the query grammar, which is currently outside the scope of the client-side JS.
(Tested locally)
@drcapulet
> Add context-awareness to autocompletion

- main/ui/ui.go
- metric_metadata/cached_metadata/cached.go
- metric_metadata/cached_metadata/cached_test.go
A huge number of goroutines could be spawned to perform background requests. (They wouldn't actually "leak" because they'd eventually either be handled or dropped, but this is still a waste of resources).
Now the `CachedMetricMetadataAPI` no longer spawns goroutines. Instead, the consumer of the API instance has to invoke the `.PerformBackgroundRequest() error` method explicitly. This is a blocking method, so the caller should do something like this:
```
cachedAPI := cached_metadata.NewCachedMetricMetadataAPI(underlyingAPI, cached_metadata.Config {
TimeToLive: time.Hour * 2,
RequestLimit: 500,
})
for i := 0; i < 10; i++ {
go func() {
for {
err := cachedAPI.PerformBackgroundRequest(
api.MetricMetadataContext{Profile: profiler}
)
if err != nil {
log.Errorf("Error performing background …
```
> Fix unintentionally creating lots of goroutines with cached metadata

- main/ui/ui.go
- metric_metadata/cached_metadata/cached.go
- metric_metadata/cached_metadata/cached_test.go
Replace `.PerformBackgroundRequest(api.MetricMetadataAPIContext) error` with `.GetBackgroundAction() func(api.MetricMetadataAPIContext) error`
@drcapulet
> Update interface for background actions in CachedMetricMetadataAPI

- metric_metadata/api.go
- metric_metadata/cached/cached.go
- metric_metadata/cached/cached_test.go
- metric_metadata/cassandra/cassandra.go
- testing_support/mocks/api.go
- timeseries/blueflood/blueflood.go
- timeseries/interface.go
Although the server won't boot up without being able to talk to Cassandra, if if goes away it'd be nice to be able to check the status of the underlying connections in the MetricMetadataAPI.
R: @Nathan-Fenner || @syamp
> Add CheckHealthy methods for metadata.MetricAPI and timeseries.StorageAPI

- tasks/canceller.go
Causing a nil pointer dereference error with an empty `TimeoutOwner`.
R: @Nathan-Fenner
> Return an empty channel on a nil Timeout

- api/timerange.go
- function/filter/filter.go
- function/filter/filter_test.go
- function/registry/registry.go
- query/tests/command_select_filter_range_test.go
- query/tests/command_select_test.go
- testing_support/mocks/combo_api.go
You can now say:
```
select
cpu | filter.mean_above(25, 1hr)
```
to select all CPU timeseries whose mean in the last hour is above 25. Or, just
```
select
cpu | filter.mean_above(25)
```
to only use the currently queried time interval.
Instead of having both functions
```
filter.highest_max(series, count)
filter.recent_highest_max( series, count, duration )
```
this PR replaces them with the new definition for `filter.highest_max`:
```
filter.highest_max( series, count [, duration] )
```
which now acts as both versions.
@drcapulet @syamp
> Filter Threshold & Filter Count Functions

- api/serieslist.go
- function/aggregate/aggregate.go
- function/aggregate/aggregate_test.go
- function/filter/filter.go
- function/filter/filter_test.go
- function/forecast/drop_function.go
- function/forecast/rolling_function.go
- function/join/join_test.go
- function/registry/registry.go
- function/tag/tag.go
- function/tag/tag_test.go
- function/transform/special.go
- function/transform/transformation.go
- function/transform/transformation_test.go
- function/value.go
- query/command/command.go
- query/tests/command_select_test.go
- query/tests/expression_test.go
- testing_support/mocks/api.go
- testing_support/mocks/combo_api.go
- timeseries/blueflood/blueflood.go
There is almost no benefit to storing the timerange of a series list in the list itself, since it will always be recorded in the associated `EvaluationContext` anyway.
Removing the `Timerange` field from `SeriesList` makes it easier to handle `SeriesList`s.
Only a few places were actually seriously effects:
* `ApplyTransformation` now has to ask for the resolution instead of finding it itself. This required only minor changes.
* `select_command_test.go` used a backend which needs `SeriesList`s to have timeranges in order to accurately query them. It's been replaced with `ComboAPI` (which has been modified slightly to support this).
* the JSON output is identical, but `QuerySeriesList` needed to be modified to report the timerange too.
@drcapulet
> Remove timerange from series list

- main/web/web.go
The default behavior for YAML decoding is to use the lowercase field name, so this doesn't actually cause any faulty behavior, but it should be fixed.
@drcapulet
> Fix Yaml Tag for Blueflood Config

- api/serieslist.go
- function/expression.go
- function/forecast/anomaly_function.go
- function/forecast/drop_function.go
- function/forecast/rolling_function.go
- function/function.go
- function/make.go
- function/registry/registry.go
- function/registry/registry_test.go
- function/tag/tag.go
- function/transform/special.go
- function/transform/transformation.go
- function/transform/transformation_test.go
- function/value.go
- query/command/command.go
- query/expression/expression.go
- query/tests/expression_test.go
To try to make it easier to define `MetricFunction`s without having to write repetitive evaluations and casts everywhere, a new function `function.MakeFunction` (possible rename to just `Make`) has been added.
It asks for an `interface{}` which is a function that acts like a metric function. It can take any of:
- `string`
- `float64`
- `time.Duration`
- `api.SeriesList`
- `function.Value`
- `function.Expression`
In addition, it can have optional arguments by requesting pointers to any of these:
- `*string`
- `*float`
- `*time.Duration`
- `*api.SeriesList`
- `*function.Value`
- `*function.Expression`
Non-optional formal arguments cannot follow optional ones. (So, for example, `(float, *string, float)` would be illegal).
For all of these, the parameters will be evaluated before they are …
> use MakeFunction in place of explicit MetricFunction everywhere possible

- api/tagset.go
- metric_metadata/cassandra/cassandra_api_test.go
- metric_metadata/cassandra/cassandra_db_test.go
- query/tests/command_names_test.go
- query/tests/command_select_test.go
- query/tests/command_test.go
- query/tests/inspect_test.go
- testing_support/mocks/api.go
- timeseries/blueflood/blueflood_test.go
- util/rules_test.go
Tag sets are unserialized in a lot of cases where they could just be literals.
@drcapulet
> Reduce Usage of `api.ParseTagSet`

- timeseries/blueflood/blueflood.go
- timeseries/blueflood/blueflood_test.go
This changes how Blueflood plans fetching. It has the following impacts:
* requesting data into the future is never a problem (Blueflood won't try to actually fetch the data, though)
* if the specified resolutions don't have monotonic (increasing) TTLs, then you'll unexpected get errors with queries. Skip resolutions with non-monotonic TTLs.
@drcapulet
> Change blueflood planning error condition

- api/timeseries.go
- demo/example-config.yaml
- function/expression.go
- function/forecast/rolling_function.go
- function/make.go
- function/registry/registry.go
- function/scalarset.go
- function/summary/summary.go
- function/value.go
- main/static/embed.html
- main/static/index.html
- main/static/script.js
- main/web/web.go
- query/command/command.go
- query/tests/command_names_test.go
- query/tests/command_select_filter_range_test.go
- query/tests/command_select_summary_test.go
- query/tests/command_select_test.go
- testing_support/assert/assert.go
- testing_support/mocks/combo_api.go
- timeseries/blueflood/blueflood.go
Let's you do summarize timeseries into tagged scalars:
```
select
cpu | summarize.mean
from -1hr to now
```
or,
```
select
cpu | aggregate.sum(group by app) | summarize.mean
from -1hr to now
```
In addition, they play nice with joins, so you can write (for example):
```
select
cpu / (cpu | aggregate.sum(group by app) | summarize.current)
from -1hr to now
```
The UI currently cannot display the results of a scalar or tagged-scalar result.
@drcapulet
> Scalar Sets for Summary Functions

- function/expression.go
- query/parser/language.peg.go
- query/tests/command_error_test.go
Previously, it could sometimes say the (highly misleading):
```
fetch limit exceeded: too many series to fetch (actual=4857 limit=5000)
```
it will now report the (much more helpful)
```
performing fetch of 4857 additional series brings the total to 9714, which exceeds specified limit 5000
```
@drcapulet
> Clarify error message

- timeseries/blueflood/blueflood.go
There are two optimizations here:
* A for-loop has been replaced with a division in the interval-planning stage
* Interval-planning is performed only once total when fetching multiple series, and not once per timeseries
@drcapulet
> Optimize Blueflood resolution selection loop into division

- timeseries/blueflood/blueflood.go
- timeseries/interface.go
- web/query.go
When these errors happen, it's impossible to tell why. Now, details will be reported *and* MQE will respond with 500 instead of 400.
Giving up the structured errors isn't really a loss, since they're not being checked anywhere anyway.
@drcapulet
> Add error details to Blueflood

- api/tagset.go
- function/builtin/tag/tag.go
- function/builtin/tag/tag_test.go
- function/registry/registry.go
Defines the `tag.copy` function that behaves thusly:
```
tag.copy(series, target, source)
```
will return a clone of `series` where the tag `target` will have the value of `source` for each series. For example,
Input:
* Series
* [1,2,3,4] `app:mqe` `host:server1`
* [5,6,7,8] `app:mqe` `host:server2`
* [1,2,4,8] `app:indexer` `host:server3`
* [2,3,5,7] `app:indexer` `host:server4`
* Target: `service`
* Source: `app`
Output:
* [1,2,3,4] `app:mqe` `host:server1` `service:mqe`
* [5,6,7,8] `app:mqe` `host:server2` `service:mqe`
* [1,2,4,8] `app:indexer` `host:server3` `service:indexer`
* [2,3,5,7] `app:indexer` `host:server4` `service:indexer`
It can be used to improve agreement for joins like `-` or `/`, as well as to improve display (by renaming a tag, via `... | tag.copy(new, old) | …
> define tag.copy

- function/builtin/forecast/anomaly_function.go
- function/builtin/forecast/drop_function.go
- function/builtin/forecast/rolling_function.go
- function/builtin/transform/special.go
- function/builtin/transform/transformation_test.go
- function/context.go
- function/expression.go
- function/make.go
- function/memoize.go
- function/registry/registry.go
- query/command/command.go
- query/expression/expression.go
- query/parser/language.peg
- query/parser/language.peg.go
- query/parser/parser.go
- query/tests/command_error_test.go
- query/tests/command_select_moving_average_test.go
- query/tests/expression_test.go
- query/tests/inspect_test.go
- query/tests/transformation_test.go
`function.EvaluationContext` is made immutable (by virtue of keeping its fields private) so that it can be reliably left untouched by metric functions. This introduces some boilerplate, but it's mostly just getter-methods for the `EvaluationContext` type.
`QueryString() string` and `Name() string` for the `Expression` interface have been replaced by `ExpressionString(DescriptionMode) string` that handles both of these *and* memoization.
There are now two kinds of expressions: `Expression` and `ActualExpression`.
The first is the kind that's used in evaluation (for example, functions should expect their arguments to be `Expression`):
```
type Expression interface {
Evaluate(EvaluationContext) (Value, error)
ExpressionString(DescriptionMode) string
}
```
The second is what expressions …
> Memoize Function Evaluations

- function/context.go
- function/memoize.go
- query/tests/inspect_test.go
Add a `WithAdditionalConstraint(predicate.Predicate)` method to `EvaluationContext` that plays nice with memoization.
Also, add a `memoizationMap` to the `EvaluationContext` which can be used to look up already-existing `memoization`s within the same query, which makes the following query much more efficient, by performing the fetch for `cpu` only once instead of twice:
```
transform.timeshift(cpu, -1w) + transform.timeshift(cpu, -1)
from -30m to now
```
> With context and better sharing for memoization

- function/builtin/forecast/rolling_function.go
- function/builtin/transform/special.go
- function/builtin/transform/transformation_test.go
- function/expression.go
- function/function.go
- function/make.go
- function/memoize.go
- query/command/command.go
- query/expression/expression.go
- query/parser/parser.go
- query/tests/expression_test.go
- query/tests/resolution_edge_test.go
- query/tests/transformation_test.go
When doing a query like
```
select
transform.moving_average(foo, 5m)
from -1d to now
```
when the edge of availability of full resolution data is at `-1d`, since you'd fetch data beyond that point with the moving average, the query would suddenly error.
Now, by inspecting the query (using annotations on the registered functions) it's possible to automatically adjust the query's resolution, increased to (say) `5m`, so that no error occurs.
It's intelligent enough to recognize that
```
select
transform.moving_average(foo, 5m) | transform.moving_average(12m)
from -1d to now
```
extends by a total of 17m, and that
```
select
transform.moving_average(foo, 5m) | transform.timeshift(-7m)
from -1d to now
```
doesn't extend it at all.
@drcapulet
> Inspect query to adjust timerange
